Add Tick Callback feature + Tick Policy Config
SomeshDaga/ROS-Behavior-Tree pull request #2
Opened 2017-12-05 23:42 UTC by SomeshDaga

- Added feature to pass in a callback function once the entire tree is executed
- Add a configurable tick policy for the control nodes (e.g. Sequence, Fallback, SequenceWithMemory, FallbackWithMemory and Parallel), which allows for certain implementations of the ActionClients.

2017-12-06 00:04 UTC, bikramak commented on behavior_tree_core/package.xml
>    <run_depend>roscpp</run_depend>
Update to using [package format="2"](http://docs.ros.org/jade/api/catkin/html/howto/format2/index.html).

2017-12-06 00:07 UTC, bikramak approved these changes
LGTM.
Minor comment: update package.xml to use  `<package format="2">`

2017-12-07 01:29 UTC, jacobperron requested changes

2017-12-07 01:29 UTC, jacobperron commented on behavior_tree_core/package.xml
> +  <depend>roslint</depend>
roslint is sufficient as a build dep: `build_depend`

2017-12-07 01:29 UTC, jacobperron commented on behavior_tree_core/CMakeLists.txt
> +list(SORT BTHeadLibrary)
Why sort?

2017-12-07 01:29 UTC, jacobperron commented on behavior_tree_core/CMakeLists.txt
> +  include_directories(${OpenGL_INCLUDE_DIRS})
I may be wrong, but on my machine it appears the correct variable is `OPENGL_INCLUDE_DIR`.

2017-12-07 01:29 UTC, jacobperron commented on behavior_tree_core/CMakeLists.txt
> +    ${OpenGL_LIBRARIES}
Similarly, `OPENGL_LIBRARIES`

2017-12-11 04:16 UTC, jacobperron approved these changes

2017-12-11 04:16 UTC, jacobperron commented on behavior_tree_core/src/behavior_tree.cpp
> +        for (int i=0; i < ctrl_node->GetChildrenNumber(); i++)
It may be more efficient/readable as:

```c++
for (auto child : ctrl_node->GetChildren())
{
  ResetFinishedNodes(child);
}
```

2017-12-11 04:16 UTC, jacobperron commented on behavior_tree_core/src/behavior_tree.cpp
> +        for (int i=0; i < ctrl_node->GetChildrenNumber(); i++)
Similarly, maybe you can use a for each loop.

2017-12-11 22:31 UTC, merged